### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by soorireddy** [jkuri/ng2-uploader#10]
Property 'findIndex' does not exist on type 'any[]'.

**Comment by jkuri** [comment]
Yes, wasnt aware its not working. Thanks.

**Comment by soorireddy** [comment]
Property 'findIndex' does not exist on type 'any[]'.

**Comment by jkuri** [comment]
Is it working?

**Comment by soorireddy** [comment]
looks like  issue with type script "TS2339: Property 'findIndex' does not
exist on type 'any[]' "

**Comment by soorireddy** [comment]
for some reasons I am getting the following error
[image: Inline image 1]

Any help would be highly appreciated.


typescript  version : "typescript": "^1.8.2"


tsconfig :
  "compilerOptions": {
    "target": "ES5",
    "declaration": false,
    "mapRoot": "",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noEmitOnError": true,
    "noImplicitAny": false
  }

**Comment by soorireddy** [comment]
unable to close window after selecting multiple files

**Comment by jkuri** [comment]
Not sure I understand you issue... where you get this error?

**Comment by soorireddy** [comment]
I had this issue in Edge browser when I tested  @ http://ng2-uploader.com/
, But now , I  tested in chrome without any issue.

**Comment by jkuri** [comment]
Okay, thanks.

**Comment by naveedahmed1** [comment]
What about replacing the below line in ng2-uploader.ts:

let queueIndex = this._queue.findIndex(x => x === file);

with the following:

var indexes = this._queue.map(function (obj, index) {
            if (obj == file) {
                return index;
            }
        }).filter(isFinite)

        let queueIndex = indexes[0];

**Comment by soorireddy** [comment]
Hi  ,

can you please update angular version :)

I am not sure if you have plans to have "DefinitelyTyped" , so that we can
use typings directly.

Regards,
Reddy

**Comment by jkuri** [comment]
I will update versions, but not sure what you mean with typings?
