### ISSUE TITLE
Do something after uploaded

### ISSUE THREAD

**Issue by truongvu2106** [jkuri/ng2-uploader#103]
I want to do something when uploading completed. But how can I know when the files uploading completed?

Thanks

**Comment by jkuri** [comment]
Hi @truongvu2106, you get the status 200 in the response which tells you that upload was successful.

**Comment by truongvu2106** [comment]
Hi @jkuri, I mean when I upload multiple files. how can I know all files uploaded?

**Comment by jkuri** [comment]
just check the response, in case of multiple uploaded files you get an array of responses.

**Comment by TonyLuo** [comment]
@jkuri  is it possible to add output.type === 'allDone' to tell all files uploaded ?
