### ISSUE TITLE
How to handle the upload on form submission

### ISSUE THREAD

**Issue by shafihuzaib** [jkuri/ng2-uploader#104]
I see that the `handleUpload` is bound to the upload event. However, my form contains some text inputs as well as a file field for image upload.

Can anyone please demonstrate the procedure, or just hint towards one!

**Comment by jkuri** [comment]
Are you looking for `data` key or you are not doing this right.

**Comment by shafihuzaib** [comment]
No, not just data.
The file gets uploaded the moment a file is selected. I, however,  want the file to be uploaded after the form (this `file` element is in) gets submitted, that is, when the form's submit button is hit.

**Comment by jkuri** [comment]
then you are looking for `autoUpload: false` option. Please check the http://ng2-uploader.com/docs

**Comment by shafihuzaib** [comment]
Yes I saw that. But then, how would the file upload when I submit the form. In the Component class, I don't have any uploader object.

**Comment by shafihuzaib** [comment]
Sorry! I probably was being careless & read incomplete. If anyone else stumbles here, the `Manual Upload` is demonstrated [here](http://ng2-uploader.com/docs#filter)

**Comment by KirilVelichkov** [comment]
@shafihuzaib - could you please explain how exactly you worked it out?

**Comment by jkuri** [comment]
@KirilVelichkov I just refactored the whole module and this should now work, please see https://github.com/jkuri/ng2-uploader/commit/587182104df11ccc3b4c6b3c3cfe55089fc83cbe.
