### ISSUE TITLE
'ng-file-select' since it isn't a known native property.

### ISSUE THREAD

**Issue by satish-pokala** [jkuri/ng2-uploader#11]
Hi, 
Thanks for the nice directive,
I am new to angular 2

I am getting this exception Can't bind to 'ng-file-select' since it isn't a known native property.
even though I am  adding following in my component

import {UPLOAD_DIRECTIVES} from 'ng2-uploader/ng2-uploader';
and added directive too 
directives: [UPLOAD_DIRECTIVES]
Please help.

**Comment by jkuri** [comment]
Can you show me the template? Actually there is a demo on the webpage where all the code is shown, maybe take a look at there.

**Comment by satish-pokala** [comment]
Hey Thanks For Your Support,

Here is my template,

<div>
<input type="file" [ng-file-select]="options"
(onUpload)="handleBasicUpload($event)"/>
</div>

Thanks & Regards,
Satish Pokala
Engineering UI Lead
Contact No: 9538780501
www.everteam.com

**Comment by jkuri** [comment]
@satish-pokala right now I really can't see what can be wrong, can you please prepare the plunkr or demo?

**Comment by satish-pokala** [comment]
Thanks again for coming back

Finally I have resolved the issue and it is working fine now

But I need some clarification

When we install ng2-uploader it does not have .js files in it.

When be build it through tsc my out put folder is build and all .js files goes
to build folder along with my files and ng2-uploader files.

If we see at ng2-uploader.js file it has line
require("ng2-uploader/ng2-uploader")

There I have changed the code to

require("../nodemodules/ng2-uploader/ng2-uploader")

Then it is working otherwise it is giving me 404 ng2-uploader

May be becuase i am using different out put folder for my typescript files


Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=5.1.1&source=email_footer_2] On Sat, Mar 05, 2016 at 3:32 pm, Jan Kuri < notifications@github.com [notifications@github.com] > wrote:
@satish-pokala [https://github.com/satish-pokala] right now I really can't see what can be wrong, can you please prepare the
plunkr or demo?

—
Reply to this email directly or view it on GitHub
[https://github.com/jkuri/ng2-uploader/issues/11#issuecomment-192615274] .[https://github.com/notifications/beacon/ABrUix8utXqpx7S57jDlUx1lJncYNtycks5pqVS1gaJpZM4HpqqJ.gif]

**Comment by satish-pokala** [comment]
If we see other npm packages it contains .js files also in it.

I am not sure whether it is making sense because i am very new to typescript and
angular.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=5.1.1&source=email_footer_2] On Sat, Mar 05, 2016 at 3:47 pm, Satish Pokala < s.pokala@everteam.com [s.pokala@everteam.com] > wrote:
Thanks again for coming back

Finally I have resolved the issue and it is working fine now

But I need some clarification

When we install ng2-uploader it does not have .js files in it.

When be build it through tsc my out put folder is build and all .js files goes
to build folder along with my files and ng2-uploader files.

If we see at ng2-uploader.js file it has line
require("ng2-uploader/ng2-uploader")

There I have changed the code to

require("../nodemodules/ng2-uploader/ng2-uploader")

Then it is working otherwise it is giving me 404 ng2-uploader

May be becuase i am using different out put folder for my typescript files


Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=5.1.1&source=email_footer_2] On Sat, Mar 05, 2016 at 3:32 pm, Jan Kuri < notifications@github.com [notifications@github.com] > wrote:
@satish-pokala [https://github.com/satish-pokala] right now I really can't see what can be wrong, can you please prepare the
plunkr or demo?

—
Reply to this email directly or view it on GitHub
[https://github.com/jkuri/ng2-uploader/issues/11#issuecomment-192615274] .[https://github.com/notifications/beacon/ABrUix8utXqpx7S57jDlUx1lJncYNtycks5pqVS1gaJpZM4HpqqJ.gif]

**Comment by jkuri** [comment]
It is recommended that you have compiled files separated from the source
files. Maybe take a look at the angular-cli tool, it has that functionality.

**Comment by NayabHussain** [comment]
@satish-pokala getting this error.. Please comment how to resolve this.

Can't bind to 'uploader' since it isn't a known native property ("rimary">
Browse
][uploader]="uploader" (change)="browse($event.target.value)" >

"):
