### ISSUE TITLE
how to react to uploads of not allowed extensions

### ISSUE THREAD

**Issue by schwamster** [jkuri/ng2-uploader#117]
while it works to restrict a user from uploading files via ngFileSelect when setting the options accordingly i am missing a way to interact with the user and show a message that the extension is now allowed.  Is there a way of doing this?

config:
` this.options = {
            url: '/api/upload',
            filterExtensions: true,
            allowedExtensions: ['image/jpg']
        };`

**Comment by jkuri** [comment]
Hi @schwamster. You mean when you update options?

**Comment by schwamster** [comment]
sry, i guess i wasn't to clear. Here is what i want to be able to do:

Given options.allowedExtensions are limited to image/jpg && options.filterExtensions is true
When a user chooses a file with extension pdf
Then upload does not start
**Then a message is displayed to the user: "Only jpg's are suppported"**

The part that i am missing is the last "Then" and i have not found a way of doing that in the example. What i could imagine as a way of doing that is another event "onUploadRejected" => for example:
`<input type="file" style="display: none;"
                           ngFileSelect
                           [options]="options"
                           (onUploadRejected)="handleUploadRejected($event)"
                           (onUpload)="handleUpload($event)" multiple>`

Or are there other ways of doing that?

**Comment by jkuri** [comment]
hmmm.. I am not aware of any hardcoded string like `Only jpg's are suppported` or such, is that maybe a browser specific reply, not sure.

**Comment by schwamster** [comment]
did not really mean a hard coded string. all i want is a way of being notified by your ng2-uploader that the file the user tried to upload does not match any in the configured options

**Comment by jkuri** [comment]
okay, sorry, got it now... can you maybe make a PR for this, I will accept it? thanks.

**Comment by schwamster** [comment]
k

**Comment by trueflywood** [comment]
(onUploadRejected) not work
