### ISSUE TITLE
/node_modules/ng2-uploader/ng2-uploader.js  not found

### ISSUE THREAD

**Issue by innovative1** [jkuri/ng2-uploader#12]
After upgrading to 0.5, I get the error that ng2-uploader can not be found. Looking under the node_modules folder, looks like the ng2-uploader.js file is not being generated from the .ts file. This was not the case with earlier versions.
Folder structure with version 0.5.0 after npm install: 

ng2-uploader
|--node_modules
|--src
|--ng2-uploader.ts
|--package.json
|--README.md
|--tsconfig.json

Worked fine with 0.3.5. File structure with version 0.3.5
ng2-uploader
|--bundles
|--config
|--src
|--tests
|--ng2-uploader.d.ts
|--ng2-uloader.js
|--ng2-uploader.js.map
|--ng2-uploader.ts
|--package.json
|--README.md
|--tsconfig.json

**Comment by final87** [comment]
Hi, I have the same error
and this Warning:
"file was not compiled because there is no a reference from tsconfig.json"
related to ng2-uploader.ts

**Comment by mwijnands** [comment]
+1. @jkuri  This package went from usable and working immediately with instructions how to load it through systemjs to.... no compiled js included and no docs on how to load it. What happened?

**Comment by jkuri** [comment]
Sorry guys, I want it to prepare to work with `angular-cli` `install` command, and the source `.ts` files are all that will be needed.
It's still usable, just copy the whole directory to somewhere in the project you have source files and then use the correct path to `ng2-uploader.ts` when importing `UPLOAD_DIRECTIVES`.

**Comment by mwijnands** [comment]
@jkuri Could you please upload a 0.5.1 package to npm that includes the .js (+ .js.map) files that come out of the .ts files? So we don't have to transpile ourselves. That is what all library developers do. And then they include a bundled .js file too (although I don't really need it).

**Comment by jkuri** [comment]
Hi @mwijnands, okay, I will do that in the near future and let you know.

**Comment by jkuri** [comment]
@mwijnands published 0.5.1 as per you request.

**Comment by mwijnands** [comment]
Thanks! :smile:
