### ISSUE TITLE
Doesn't work with AoT 

### ISSUE THREAD

**Issue by nastakhov** [jkuri/ng2-uploader#137]
Running node_modules/.bin/ngc" -p tsconfig-aot.json got error:

Error: Unexpected value 'Ng2UploaderModule' imported by the module 'CoreModule'

Missing .metadata.json file

https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.jrh3je2su

**Comment by theromis** [comment]
getting same issue
```
➜  ~ ionic info

Your system information:

Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v7.1.0
Xcode version: Xcode 8.1 Build version 8B62```

what can I do to make ionic build work?

**Comment by CelsoSantos** [comment]
This issues should now be fixed with the latest version

**Comment by jkuri** [comment]
https://github.com/jkuri/ng2-uploader/commit/c1042498aedecd387262aadc65f85cbc89dc77dd
