### ISSUE TITLE
files.forEach is not a function

### ISSUE THREAD

**Issue by DeyuanTan** [jkuri/ng2-uploader#139]
code:
![image](https://cloud.githubusercontent.com/assets/8966624/20645803/349b085a-b4a4-11e6-8a70-e59486a4b105.png)

![image](https://cloud.githubusercontent.com/assets/8966624/20645806/7488585a-b4a4-11e6-8426-68aa0cf567b2.png)

Error:
![image](https://cloud.githubusercontent.com/assets/8966624/20645804/4ea6b3f2-b4a4-11e6-867f-731069fe9c88.png)
![image](https://cloud.githubusercontent.com/assets/8966624/20645813/9a158868-b4a4-11e6-890d-71eb8486cb57.png)

**Comment by jkon** [comment]
I'm having this problem too. Did you figure out a fix?

**Comment by DeyuanTan** [comment]
FileList is a Object {}, Not a Array Object. 
var a = {}; typeof a.forEach = undefined;
var b= []; typeof b.forEach = 'function';

**Comment by jkon** [comment]
So, did you fork and fix it yourself? Or is there a way to get it to send Files as an array instead of a FileList object?

**Comment by DeyuanTan** [comment]
my code: 
![image](https://cloud.githubusercontent.com/assets/8966624/22050253/37ab6a28-dd74-11e6-9e29-d279fca86157.png)
