### ISSUE TITLE
False Boolean options revert back to defaults

### ISSUE THREAD

**Issue by zatomik** [jkuri/ng2-uploader#14]
Hi, having trouble setting bool options, maybe I'm missing something, but for eg:
```
  options: Object = {
    url: 'http://localhost:10050/upload',
    autoUpload: false
  };
```
The following line in the service will always return the default again (true)
` this.autoUpload = options && options.autoUpload || this.autoUpload; `

Maybe something like this instead:
`this.autoUpload = options && options.autoUpload !== false;`

I can submit a PR later if you agree,
Cheers

**Comment by jkuri** [comment]
Hi, sure. PRs are welcome.
