### ISSUE TITLE
Show image thumbnail

### ISSUE THREAD

**Issue by rkrayovskyy** [jkuri/ng2-uploader#15]
Does it support functionality to show thumbnail of the image right after dropping/uploading it?
If not, any plans to implement it soon?

**Comment by jkuri** [comment]
Hi Roman. Currently this is not supported but I don't see a reason why should not be in the future. If you maybe have some time PRs are welcome. Otherwise it will be implemented in the future but unsure when.

**Comment by rkrayovskyy** [comment]
Jan,
got it, thanks. Will take a look at it when I have a chance.


Roman

**Comment by jkuri** [comment]
http://ng2-uploader.com/advanced

**Comment by mkariti** [comment]
Hi,
Link is not working...
How can I implement it?
Thanks
