### ISSUE TITLE
npm install error.

### ISSUE THREAD

**Issue by kolkov** [jkuri/ng2-uploader#150]
![image](https://cloud.githubusercontent.com/assets/3740898/20933247/88744f0e-bbe8-11e6-9367-c2efcabdb283.png)

**Comment by j-c-levin** [comment]
Happened to me on 1.5.7 and 1.5.6.  Installs fine on 1.5.5 though ("ng2-uploader": "1.5.6")

**Comment by deeg** [comment]
I don't get this error on 1.5.7, but on npm install I get asked to supply a name which creates a component.

I don't believe the npm install process should ever ask for input seeing as it is run automatically most of the time. It doesn't seem like we should have to have the install process put in an input for this.

**Comment by kolkov** [comment]
![image](https://cloud.githubusercontent.com/assets/3740898/20982681/99e32aca-bcca-11e6-8e22-528bcd79900d.png)

**Comment by jkuri** [comment]
https://github.com/jkuri/ng2-uploader/commit/ca718f393dd0318b908d1914fbe4296e53adfc99
