### ISSUE TITLE
angular2-polyfills.js:1243 Error: SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by rocco-scaramuzzi** [jkuri/ng2-uploader#23]
Hi There,

when adding the ng2-oploader I got this run-time error: Error: SyntaxError: Unexpected token <(…) at angular2-polyfills.js:1243. Any reason why? I am using SystemJS to boostrap the app and I am using angular-quick-start  2.0.0-beta.9.

It will be very appreciated any help.
Thanks

**Comment by jkuri** [comment]
Hi, how did you include it to your project? If you can create a plunkr I can take a look. 
Cheers

**Comment by rocco-scaramuzzi** [comment]
Hi Jan, thanks for your answer. I have just fixed it by including reference in System.Config packages and paths as following:
//*****
<script>
        System.config({
            packages: {
                "/poster-manager-app": {
                format: 'register',
                defaultExtension: 'js'
                },
                'node_modules/ng2-uploader': {
                    format: 'register',
                    defaultExtension: 'js'
                }
            },
            paths: {
                "ng2-uploader": "node_modules/ng2-uploader/ng2-uploader"
            }

        });
        System.import('/poster-manager-app/main')
                .then(null, console.error.bind(console));
    </script>
//*****
Instead at the beginning I was including with script tag <script src="../../node_modules/ng2-uploader/ng2-uploader.js"></script>.

I think adding that in System.Config should be the right way to fix that issue. Thank so much for the simple and clean directive, I will start to use it.

Cheers,
Rocco

**Comment by jkuri** [comment]
Nice to hear that! Sure, no problem.
