### ISSUE TITLE
browser.d.ts not found - Angular2 v2.0.0-beta.13

### ISSUE THREAD

**Issue by beatadelura** [jkuri/ng2-uploader#25]
File `ng2-uploader/node_modules/angular2/typings/browser.d.ts` is not found.

To get around it I had to remove `/// <reference path="node_modules/angular2/typings/browser.d.ts" />` from `ng2-uploader.ts` and `ng2-uploader.d.ts`

**Comment by jenghung** [comment]
the same problem....

**Comment by tan9** [comment]
Since PR #30 was merged, this issue will be gone once @jkuri released a new version.

**Comment by msegers** [comment]
The question is, when will he ;-)

**Comment by tan9** [comment]
@msegers this is a question only @jkuri can answer you.

However, you can reference to the exact commit at GitHub in your package.json like this:
```json
"dependencies": {
  "ng2-uploader": "git+https://github.com/jkuri/ng2-uploader.git#944808d2034af7128fbbf2036643edb0426a3924",
  ...
```

**Comment by ashfon** [comment]
I have a same problem, but when I remove /// <reference path="node_modules/angular2/typings/browser.d.ts" /> code from ng2-uploader.tx file, i get more errors like Cannot find name 'Map'.
I am using Angular2 RC1. As part of ng2-uploader download beta 16 is install in subfolder. Any suggestions on how to fix this?

**Comment by jkuri** [comment]
This is now resolved.
