### ISSUE TITLE
 error TS2654: Exported external package typings file cannot contain tripleslash references.

### ISSUE THREAD

**Issue by MrCroft** [jkuri/ng2-uploader#32]
This happens when I simply try to import:
import {UPLOAD_DIRECTIVES} from "ng2-uploader/ng2-uploader";

I've attached the entire console output (it also said something about gulp, but after a restart it didn't anymore, only the 2 TS errors):
[console_output.txt](https://github.com/jkuri/ng2-uploader/files/231916/console_output.txt)

"error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition."
"error TS6053: File 'D:/wamp/www/mysite/node_modules/ng2-uploader/node_modules/angular2/typings/browser.d.ts' not found."

If I remove the reference /// <reference path="node_modules/angular2/typings/browser.d.ts" /> (from both .ts and .d.ts) like it says in #25, then I don't get any errors, console says everything went fine, but the uploader doesn't work. Actually, if I modify anything in my app while having the uploader imported (let's say even a simple text), then build (no errors), then refresh... nothing's changed. All files remain like they were before including the uploader, so I guess nothing transcompiles... even if console says so. But without ng2-upload, everything's fine. That's really weird...

**Comment by MrCroft** [comment]
It seems that there was a chrome caching issue regarding ajax requests and the transcompiled components. disabled cache from DevTools and app changes were reflected immediately. However, I'm getting a zone "unexpected token" error from angular2-polyfills. But that's another issue, don't know what to do with that yet.

**Comment by jkuri** [comment]
Hey @MrCroft, did you try to do it as its done in demo? What angular version are you using?

**Comment by ashfon** [comment]
Have you got any solution, i am having exactly same issue. I am working on Angular2 RC1, when I download ng2-uploader v0.5.1, it also downloaded Angular2  beta17 in subfolder.
