### ISSUE TITLE
Can't bind to 'uploader' since it isn't a known native property

### ISSUE THREAD

**Issue by chambersDon** [jkuri/ng2-uploader#35]
I had this working before the release candidate upgrade.  Now it compiles but I get this runtime error:
```
EXCEPTION: Template parse errors:
Can't bind to 'uploader' since it isn't a known native property ("-over': hasBaseDropZoneOver}"
                 (fileOver)="fileOverBase($event)"
                 [ERROR ->][uploader]="uploader"
                 class="well my-drop-zone">
                <!--<h3>Upload Fi"): FileUploadComponent@10:17
Can't bind to 'uploader' since it isn't a known native property ("
                <!--<h3>Upload Files</h3>-->

                <input type="file" ng2-file-select [ERROR ->][uploader]="uploader" multiple /><br />

```

Here is a snippet from my component.ts:
```
@Component({
    selector: 'file-upload',
    templateUrl: 'app/components/fileUpload/fileUpload.component.html',
    directives: [FILE_UPLOAD_DIRECTIVES, NgClass, NgStyle, CORE_DIRECTIVES, FORM_DIRECTIVES]
})

export class FileUploadComponent {
    public uploader: FileUploader = null;
    public hasBaseDropZoneOver: boolean = false;
    public hasAnotherDropZoneOver: boolean = false;

    constructor(private _config: ConfigService, private _sessionService: SessionService) {
        this.uploader = new FileUploader({ url: this._config.getUrl('/api/fileupload/upload') });
        this.uploader.authToken = 'Bearer ' + this._sessionService.Session.id_token;
    }

```

And here is the relevant markup in the template where the error occurs.
```
            <div ng2-file-drop
                 [ngClass]="{'nv-file-over': hasBaseDropZoneOver}"
                 (fileOver)="fileOverBase($event)"
                 [uploader]="uploader"
                 class="well my-drop-zone">
                <!--<h3>Upload Files</h3>-->

                <input type="file" ng2-file-select [uploader]="uploader" multiple /><br />


```

Any ideas?

**Comment by chambersDon** [comment]
Solved.  The directive is now ng2FileDrop, not ng2-file-drop.

**Comment by NayabHussain** [comment]
@chambersDon getting this error.. Please how to resolve this.

Can't bind to 'uploader' since it isn't a known native property ("rimary">
                  Browse
                  <input type="file" class="upload" ng2FileSelect [ERROR ->][uploader]="uploader" (change)="browse($event.target.value)" >
                  </div>
             "):

**Comment by escarabin** [comment]
I am kind of stuck with this error too, can someone post a code sample on how to solve this please?

**Comment by escarabin** [comment]
For those encountering this problem, I finally solved it.
First you have to import {FileDropDirective} from ng2-file-upload :
```
import {FileSelectDirective,
        FileDropDirective,
        FileUploader} from 'ng2-file-upload/ng2-file-upload';
```

Then pass 'FileDropDirective' in your component's directives

**Comment by yeelan0319** [comment]
@escarabin 
I am getting this error when using jspm to bundle the js files for serving purpose, but not getting it when running separately with systemjs. May I know what tool you to bundle them to avoid this error in production? Thanks!

**Comment by jkuri** [comment]
@yeelan0319 I suppose your tool for bundle is eliminating the code that is actually in use. If you are using `webpack` see the configuration examples for production at https://github.com/angular/angular-cli or https://github.com/AngularClass/angular2-webpack-starter and compare it to yours. I had similar problems before and it was an issue with the production config.
