### ISSUE TITLE
any plan on fixing typescript error? should be pretty simple one

### ISSUE THREAD

**Issue by collapsarzhang** [jkuri/ng2-uploader#36]
```
$APP_ROOT/node_modules/ng2-uploader/ng2-uploader.ts(1,1): error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.

$APP_ROOT/node_modules/ng2-uploader/ng2-uploader.ts(1,1): error TS6053: File '$APP_ROOT/node_modules/ng2-uploader/node_modules/angular2/typings/browser.d.ts' not found.
```

**Comment by estebanjrojas** [comment]
the code is actually up to date but the npm package isn't.

**Comment by benelliott** [comment]
@jkuri could you release a new version that uses this configuration please? It's quite awkward to have to declare the repo master as a dependency and then build the library from source as part of my deployment.

**Comment by jesion** [comment]
Guys, generally great work. But this error is a pain. Any plans to have the npm package to be in sync with your github's master?

**Comment by apkostka** [comment]
I believe this issue can be closed, as the npm package has been updated per [this comment](https://github.com/jkuri/ng2-uploader/pull/38#issuecomment-227613995). @jkuri ?

**Comment by jkuri** [comment]
Yes, thanks @apkostka.
