### ISSUE TITLE
src/services/ng2-uploader.js references to angular2/core which breaks

### ISSUE THREAD

**Issue by 5amfung** [jkuri/ng2-uploader#40]
Although `src/services/ng2-uploader.ts` correctly references to `@angular/core` but the transpiled verson `src/services/ng2-uploader.js` still references to `angular2/core` which I think is incorrect.

When I use ng2-uploader in my project, I got error complaining about `angular2` not existed.

It's possible that the version uploaded to npmjs is bad.

**Comment by Davy-F** [comment]
I agree. 

`System.register(['angular2/core'], `

Should be removed from src/services/ng2-uploader.js.

**Comment by jkuri** [comment]
This is resolved with the new version.
