### ISSUE TITLE
connect err!

### ISSUE THREAD

**Issue by q986872053** [jkuri/ng2-uploader#41]
I got a err!

POST http://localhost:9000/law/file/upload

"NetworkError: 404 Not Found - http://localhost:9000/law/file/upload"
upload
（course：CORS less 'Access-Control-Allow-Origin'）。

**Comment by ohader** [comment]
That one is triggered by your browser since CORS headers are insufficient.
The solutions is to let your web-server send accordant `Access-Control-*` HTTP headers, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Origin

**Comment by jkuri** [comment]
Yes, @ohader is right. Related: https://github.com/jkuri/ng2-uploader/issues/44.
