### ISSUE TITLE
data.done is set instead of data.error despite of HTTP 500

### ISSUE THREAD

**Issue by mrStudent123** [jkuri/ng2-uploader#44]
The pasted error below is not an error with the uploader (server/auth), but it is not recognized by ng2-uploader and the flags are set wrong.

XMLHttpRequest cannot load ....... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 500.

**Comment by jkuri** [comment]
This is a problem with your backend API, you must allow CORS to make this work.
