### ISSUE TITLE
fails to load 'angular2/core.js'

### ISSUE THREAD

**Issue by shadeeka** [jkuri/ng2-uploader#47]
could not able to  use this component with angular2 latest release rc.3 or rc.4.
it gives error cannot found module angular2/core when running in system.js environment
can you please help me 
thank you

**Comment by avegpatekar** [comment]
we are also facing the same issue ..do u have any solution??

**Comment by jkuri** [comment]
Hey. I will update this later tonight.

**Comment by jkuri** [comment]
Done.
