### ISSUE TITLE
Unable to find typings in the package

### ISSUE THREAD

**Issue by xeoneux** [jkuri/ng2-uploader#48]
After latest update from `0.5.2` to `0.5.4`, this error gets thrown:

```
Error: ENOENT: no such file or directory, open '~/node_modules/ng2-uploader/typings/index.d.ts'
```

Is it due to the missing typings along with the package?

**Comment by jkuri** [comment]
Thanks for notice. Should be resolved with https://github.com/jkuri/ng2-uploader/commit/f439329a7a55b6dfa09e118464e359e425e9a0d7.
