### ISSUE TITLE
Integrating in angularcli

### ISSUE THREAD

**Issue by muscaiu** [jkuri/ng2-uploader#49]
Is there any tutorial or example for adding ng2-uploader to angularcli?

I posted the full question and details here: 
http://stackoverflow.com/questions/38565757/import-ng2-uploader-in-angularcli

**Comment by jkuri** [comment]
Hey @muscaiu, 

something like the following should work:
```js
// angular-cli-build.js
vendorNpmFiles: [
...,
'ng2-uploader/ng2-uploader.js'
]
```

```ts
// system-config.ts
const map: any = {
  'ng2-uploader': 'vendor/ng2-uploader'
};

/** User packages configuration. */
const packages: any = {
  'ng2-uploader': {
    main: 'ng2-uploader.js'
  }
};
```

Let me know if you need further help.

**Comment by dindong** [comment]
doesnt work for me.

zone.js:101 GET http://localhost:4200/vendor/ng2-uploader/src/services/ng2-uploader.js 404 (Not Found)

**Comment by jkuri** [comment]
Try this in `angular-cli-build.js`:
```
vendorNpmFiles: [
  ...,
  'ng2-uploader/**/*.js'
]
```
If it doesn't work please let me know. I'll make a working example.

**Comment by dindong** [comment]
works. great. thank you.

**Comment by jkuri** [comment]
no problem. glad you got it working.
