### ISSUE TITLE
Typescript duplicates in dependencies' typings

### ISSUE THREAD

**Issue by dragGH102** [jkuri/ng2-uploader#52]
I'm not sure why but, while on the first app run it worked, I couldn't compile typescript files any longer because I was gettins errors such as:

         node_modules/ng2-uploader/typings/globals/es6-collections/index.d.ts(28,5): error TS2300: Duplicate identifier 'size'.
       node_modules/ng2-uploader/typings/globals/es6-promise/index.d.ts(8,15):: error TS2300: Duplicate identifier 'Promise'.

I solved the issue by **commenting out completely those 2 files**.
But this shouldn't be normal (to need overriding an external module)

Tested on **Angular RC2**

**Comment by nnixaa** [comment]
Same here https://github.com/akveo/ng2-admin/issues/113

**Comment by jkuri** [comment]
This should be resolved with `0.5.6`.

**Comment by dragGH102** [comment]
it seems so. thanks @jkuri !
