### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by supgeek-rod** [jkuri/ng2-uploader#53]
I use the ionic2

1. import {UPLOAD_DIRECTIVES} from 'ng2-uploader/ng2-uploader';
2. directives: [UPLOAD_DIRECTIVES],

then an error
```
/Users/SupeRodv2/dev4living/HeyCommunity/HeyCommunity-frontend/node_modules/ng2-uploader/ng2-uploader.ts:1
import {Ng2Uploader} from './src/services/ng2-uploader';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

🆘 help me

**Comment by jkuri** [comment]
Hey @supgeek-rod, you should include `ng2-uploader` as
```ts
import {Ng2Uploader} from 'ng2-uploader';
```
Please check the demo page and correlated documentation.

**Comment by supgeek-rod** [comment]
@jkuri no,  include `import {Ng2Uploader} from 'ng2-uploader';`  report not found this file

**Comment by jkuri** [comment]
Can you share your code and I will take a look?

**Comment by supgeek-rod** [comment]
see https://github.com/dev4living/HeyCommunity-frontend, new-master branch

**Comment by jkuri** [comment]
okay, one moment..

**Comment by jkuri** [comment]
```ts
import {Ng2Uploader} from 'ng2-uploader/ng2-uploader';
```

**Comment by supgeek-rod** [comment]
Not include `directives: [UPLOAD_DIRECTIVES]`？

It will be give error as follows
```
38806EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'ng-file-select' since it isn't a known native property ("
  <input type="file" 
       style="display:none;"
       [ERROR ->][ng-file-select]="options"
       (onUpload)="handleUpload($event)"
       multiple>
"): TimelineCreatePage@38:7
```

**Comment by supgeek-rod** [comment]
Please checkout https://github.com/dev4living/HeyCommunity-frontend, dev-ng2uploader branch.
Compare the last two commits

**Comment by jkuri** [comment]
```ts
import {UPLOAD_DIRECTIVES} from 'ng2-uploader/ng2-uploader';
```

**Comment by supgeek-rod** [comment]
At first I was doing, it still does not work
