### ISSUE TITLE
Sourcemap hardcoded path

### ISSUE THREAD

**Issue by FabianMeul** [jkuri/ng2-uploader#63]
When including the library in an Angular2 Typescript JSPM environment, I receive errors regarding the loading of SourceMaps. The path to the SourceMap seems to contain hardcoded elements, causing the load to fail.

This is the error I'm getting:
> Failed to parse SourceMap: https://***:8500/Users/jan/Dev/github/ng2-uploader/index.js.map

**Comment by jkuri** [comment]
This should now be resolved.
