### ISSUE TITLE
How can I add more params along with the file upload?

### ISSUE THREAD

**Issue by mickeychu** [jkuri/ng2-uploader#69]
How can I add more params (like {user_id: 2, job_id: 3}) along with the file when uploading?

Many thanks!

**Comment by Ks89** [comment]
This question is very important. Please, can someone explain how we can do that?

**Comment by jkuri** [comment]
It is not currently possible, but I agree it should be in the future. It's on my todo list.

**Comment by jkuri** [comment]
It is now possible since `1.0.0`. You just past `data: {}` to `options` object. For more information please see [documentation](http://ng2-uploader.com/docs).
