### ISSUE TITLE
Demo ng2-uploader.com is down

### ISSUE THREAD

**Issue by leocaseiro** [jkuri/ng2-uploader#70]
Hi @jkuri,
Thanks for this amazing lib. It's pretty easy to implement.

Unfortunately, the demo website is down, perhaps publishing as a `gh-pages` would be easier to maintain?

Thanks

**Comment by jkuri** [comment]
Hi,

it does work for me. I moved demos to another VPS recently, maybe you still have stored previous DNS records in your browser cache.

Cheers, Jan

**Comment by leocaseiro** [comment]
Honestly, I've tried a few more times and it did work once, but it's down again.
