### ISSUE TITLE
Error: ReferenceError: NgFileSelect is not defined(…)

### ISSUE THREAD

**Issue by cissecedric** [jkuri/ng2-uploader#71]
Hello,

I'm using this code but I get the error NgFilePreview is not defined, with angular rc.6 (wich I currently use) it is not possible to add directives in @component, I don't know if it can explain the problem?

import {Component, NgZone} from '@angular/core';
import {UPLOAD_DIRECTIVES} from 'ng2-uploader/ng2-uploader';

@Component({
  selector: 'image-preview',
  templateUrl: 'app/components/image-preview/image-preview.html',
})
export class ImagePreview {
  **@ViewChild(NgFileSelect) private fileSelect: NgFileSelect;**
  previewData = ''
  options: Object = {
    url: 'http://localhost:10050/upload',
    previewUrl: true,
    autoUpload: false
  };

**Comment by jkuri** [comment]
Hi, on the demo link there's a link to sample app which is based on RC6.
