### ISSUE TITLE
how to use / implement the demo for rc.6 ?

### ISSUE THREAD

**Issue by cissecedric** [jkuri/ng2-uploader#73]
Hi,

I've just download the demo app 'ng2-uploader-demo' for rc.6, but how can I use/implement / test it ?
npm start won't work ..

Could someone tell me what am I missing ?
Regards.

**Comment by jkuri** [comment]
@cissecedric first run `npm install` then run it with `npm run serve`. This will open your browser with the app. Please let me know if you need further help.

**Comment by cissecedric** [comment]
Thankyou Jurki, 

But I get a few erros, runing npm serve:
[npm-debug.txt](https://github.com/jkuri/ng2-uploader/files/454033/npm-debug.txt)
Regards,

**Comment by jkuri** [comment]
No problem :-).
Can you try to update `node` to the latest version, otherwise there's some issue with the starter this demo is based on Windows. However this is not the problem with the `ng2-uploader` itself and the demo app gives you an example how it should be included.

**Comment by cissecedric** [comment]
I updated node v6.3.0. same error after...  I think it's a problem with "rollup". 
I check and tell you...
Regards and thank you,
