### ISSUE TITLE
How to catch the response from the server after uploading?

### ISSUE THREAD

**Issue by mickeychu** [jkuri/ng2-uploader#75]
Thank you for the new version, now the uploading works great.
However, I still need to catch the response from the server, how can I achieve that?

Looks like I can not add **subscribe** directly after the **uploadEvents.emit**

```
startUpload() {
    this.uploadEvents.emit('startUpload').subscribe();
}
```

**Comment by jkuri** [comment]
Please check https://github.com/jkuri/ng2-uploader#basic-example. It includes full example how to achieve that.

**Comment by mickeychu** [comment]
Thank you, it works!!!

**Comment by KirilVelichkov** [comment]
@mickeychu , could you please show how you`ve managed it with the "startUpload()" function?
