### ISSUE TITLE
Cannot change url after component initialization

### ISSUE THREAD

**Issue by wouterhummelink** [jkuri/ng2-uploader#80]
Hi, 

I'm trying to get an uploader to work. However in my API the URL for the file upload is dependent on the parent object ID. I've added a property that contains the ID and when the upload happens the options object contains the correct URL, but the actual upload does not.

How can I set the upload url at the time the upload starts?

**Comment by jkuri** [comment]
https://github.com/jkuri/ng2-uploader/pull/84
