### ISSUE TITLE
typings property missing in package.json when installing from npm

### ISSUE THREAD

**Issue by danyhoron** [jkuri/ng2-uploader#85]
Could you please add:
"typings": "ng2-uploader.d.ts",
to the package.json when installing through npm, so VSCode will pick it up?

Thank you.

**Comment by jkuri** [comment]
Will do.

**Comment by jkuri** [comment]
https://github.com/jkuri/ng2-uploader/commit/66f7ef62f9fef078cb4dc2b82e294bf15fdc68f0
