### ISSUE TITLE
[events] property not working with Angular 2 final

### ISSUE THREAD

**Issue by Nick-Triller** [jkuri/ng2-uploader#88]
The startUpload event has no effect when Angular 2 final is used.

ng-file-select.ts contains the following check:
```typescript
if (this.events instanceof EventEmitter) {
    this.events.subscribe((data: string) => {
         if (data === 'startUpload') {
            this.uploader.uploadFilesInQueue();
          }
     });    
 }
```

This instanceof check always fails when Angular 2 final is used, therefore the subscribe method is never called.

**Comment by jkuri** [comment]
Not sure where you got `startUpload` event name though.

**Comment by Nick-Triller** [comment]
Please see ng2-uploader/src/directives/ng-file-select.ts, line 55.

**Comment by Nick-Triller** [comment]
Please see ng2-uploader/src/directives/ng-file-select.ts, line 55.

Some more details:

Template:
```html
<input type="file" 
          ngFileSelect
          [options]="options"
          [events]="uploadEvents"
          (onUpload)="handleQuestionnaireUpload($event)"
           id="questionaire-upload"
           class="upload">
 <button class="btn btn-primary" (click)="startUpload()">Hochladen</button>
```

Component:
```Typescript
export class QuestioningTypeDetailsComponent implements OnInit {
    questioningType = <QuestioningType>{};
    options;
    uploadEvents: EventEmitter<any> = new EventEmitter();

    constructor(private questioningTypeService: QuestioningTypeService,
                private router: Router,
                private activatedRoute: ActivatedRoute,
                private notificationsService: NotificationsService,
                private errorService: ErrorService) {
    }

    ngOnInit() {
        this.activatedRoute.params.subscribe((params: Params) => {
            // Get session id
            const sessionId: string = Cookie.get("JSESSIONID");
            // Get XSRF header value
            const xsrfToken: string = Cookie.get("XSRF-TOKEN");
            // Set ngFileSelect options
            this.options = {
                url: '/api/questioningtypes/' + params["id"] + '/questionaire',
                autoUpload: false,
                filterExtensions: true,
                allowedExtensions: ['application/pdf'],
                calculateSpeed: false,
                customHeaders: {
                    'X-XSRF-TOKEN': xsrfToken
                },
            };
            this.getQuestioningTypeData(+params["id"]);
        });
    }

    startUpload() {
        console.debug("START UPLOAD CALLED");
        console.debug("uploadEvents instanceof EventEmitter? " + typeof this.uploadEvents);
        this.uploadEvents.emit("startUpload");
    }
```

The startUpload function is never called because the EventEmitter that is passed via [events] fails the `instanceof EventEmitter` check.

**Comment by jkuri** [comment]
I suggest you use code from examples which confirmed works.

**Comment by Nick-Triller** [comment]
Thank you for your fast feedback. :) I will try to reproduce this bug with the example code.

**Comment by jkuri** [comment]
no problem, I just don't see a reason complicating things if the example code works for all the users and no-one complains about it.

**Comment by Nick-Triller** [comment]
I managed to reproduce the same bug when using the last example ("Filter Allowed Extensions with Preview Enabled and Manual Upload Example") on [this ](http://ng2-uploader.com/docs) page with Angular 2 final. This is the only example which uses the [events] property. 

Changing ng-file-select.ts from
`
if (this.events instanceof EventEmitter) {
    this.events.subscribe((data: string) => {
         if (data === 'startUpload') {
            this.uploader.uploadFilesInQueue();
          }
     });    
 }
`
to
`
if (this.events) {
    this.events.subscribe((data: string) => {
         if (data === 'startUpload') {
            this.uploader.uploadFilesInQueue();
          }
     });    
 }
`
solves the problem.

**Comment by jkuri** [comment]
thanks Nick, can you please provide a PR which solves the issue and I'll accept it right away?

**Comment by Nick-Triller** [comment]
Sure, will do.

**Comment by Nick-Triller** [comment]
Solved
