### ISSUE TITLE
Can't upload the same file twice

### ISSUE THREAD

**Issue by mwijnands** [jkuri/ng2-uploader#9]
When uploading the same file again - even after switching to another view (e.g. component) and back again - nothing happens.

It is probably intended behavior when the uploader is visible and you just upload the same file again (you can see that in the demo site). But in my case I switch to another component (i.e. click a menu button and go to another view via routing) and then navigate to the upload component again to upload the same file. Nothing happens. Can I maybe reset the uploader in some way when my component is constructed, as a workaround?

**Comment by jkuri** [comment]
This is not intended behavior. Thanks for noticing. I believe the fix would be to reset the `<input type="file">` value as upload directive is working onChange; if you select the same file again actually the value doesn't change. Didn't try but I think this is the solution.

**Comment by mwijnands** [comment]
Is it fixed?

**Comment by tb** [comment]
@jkuri the solution you described works.

    <input #uploader type="file" ngFileSelect ... (onUpload)="onUpload()">

    @ViewChild('uploader') uploaderInput: ElementRef;

    onUpload() {
      // ....
      this.uploaderInput.nativeElement.value = '';
    }

or directly in template:

    <input #uploader type="file" ngFileSelect ... (onUpload)="uploader.value=''">

Dont you think this should be done [here](https://github.com/jkuri/ng2-uploader/blob/8cb23d95f3c7ee7f4ce46db04358c8eee5fb99d6/src/directives/ng-file-select.ts#L41) ? Maybe as some option like `fieldReset: true`?

**Comment by jkuri** [comment]
@tb thank you! Maybe could be done there, can you maybe provide a PR with that example to be included in README? I would really appreciate it as a lot of users are asking this question. Thanks.

**Comment by tb** [comment]
@jkuri Ill make PR during weekend

**Comment by jkuri** [comment]
okay, thanks

**Comment by filipefreitas82** [comment]
Hi

I'm having this issue with the latest version (2.1.6)
And I can't find the fix code in  'master'

Any idea?

**Comment by lukasz-galka** [comment]
the same situation with 2.2.0

**Comment by jkuri** [comment]
@lukasz-galka can you propose a solution maybe?

**Comment by JDVS20** [comment]
I resolved this issue using this,

onChange(event:any):void{
event.srcElement.value = "";
}

**Comment by vickyjain93** [comment]
I am facing a issue where I am validating the file from the back end and if the validation fails, i get response as 400 in my uploaded file, now i need to upload the same file again so i am calling upload Input function again, but all i get is event as done and the middle part like start, uploading is skipped. Is there any way to reset the file data and send the file again without making user to select the file again?
