### ISSUE TITLE
Modify 'options' after onInit

### ISSUE THREAD

**Issue by josealonsogarcia** [jkuri/ng2-uploader#91]
Hi, 

I would like to know if I can modify the 'options' once onInit is executed. Just in my case I want to add, in the "data" field", some data relative to the file like description added by the user.

Thanks!

**Comment by jkuri** [comment]
hey! yes, that is available since https://github.com/jkuri/ng2-uploader/commit/fdb99b149e9038d6f120dda567c3d3e1dd801159.

**Comment by josealonsogarcia** [comment]
Cool! Thanks!

**Comment by dominickp** [comment]
Could someone explain how this is done? I can't seem to figure out how to modify the options after onInit.

```js
this.basicOptions.url = this.endpoint;
```

Provides an undefined url error on upload if done after onInit and before the startUpload event is called.

**Comment by Mcs-developer** [comment]
Hi @josealonsogarcia, Does this work for you? I tried but I can not fix it.

```
this.options.data = { id: this.experience.id };
this.inputUploadEvents.emit('startUpload');
```
options.data.id changes when I click on a button.
