### ISSUE TITLE
Error: Uncaught Unexpected value 'NgFileDropDirective' declared by the module 'AppModule'

### ISSUE THREAD

**Issue by kelvinrolex** [jkuri/ng2-uploader#94]
I was using SystemJs for my Angular2 project and everything works fine until I changed to Webpack and I started getting this error in the console: Uncaught Unexpected value 'NgFileDropDirective' declared by the module 'AppModule'.

Please how do i solve this issue...

**Comment by jkuri** [comment]
@kelvinrolex `NgFileDropDirective` is not existent and does not work. You need to use `NgFileDrop` so its just a typo.

**Comment by kelvinrolex** [comment]
Ok thanks for your response, but the issue has been resolve, I was imprting it from my vendor.ts file while it has already been imported from my app.module.ts file, so when I removed the import from the vendor.ts file the error was fix. Thank you once more for your response and I must say that this ng2-uploader is the best I have seen so far.
